/* fofo hair — product catalog.
   `vessel` picks the illustrated packaging shape, `tint` is the liquid/label colour. */
window.FOFO_PRODUCTS = [
  {
    id: 'cloud-wash',
    name: 'Cloud Wash',
    kind: 'Cleanse',
    tagline: 'Sulfate-free cushioning shampoo',
    desc: 'A low-lather, pH-balanced cleanse that lifts buildup without stripping the natural oils your lengths depend on. Rice amino acids leave strands swollen with slip, never squeaky.',
    hero: 'Rice amino acids · oat beta-glucan',
    types: ['straight', 'wavy', 'curly', 'coily'],
    concerns: ['dryness', 'frizz', 'scalp'],
    sizes: [{ label: '250ml', price: 28 }, { label: '500ml', price: 46 }],
    rating: 4.8, reviews: 2140,
    vessel: 'pump', tint: '#E8C9A8', badge: 'Bestseller',
    ingredients: ['Rice amino acids', 'Oat beta-glucan', 'Coco-glucoside', 'Panthenol', 'Glycerin'],
    howto: 'Massage a coin-sized amount into a wet scalp for sixty seconds. Let the rinse water carry it down your lengths — no need to scrub the ends.'
  },
  {
    id: 'plush-conditioner',
    name: 'Plush Conditioner',
    kind: 'Condition',
    tagline: 'Slip-rich detangling conditioner',
    desc: 'Our cupuaçu whip, reformulated for hair. Gives wet strands the kind of slip that makes a wide-tooth comb glide from root to tip — then rinses clean with zero film.',
    hero: 'Cupuaçu butter · behentrimonium',
    types: ['wavy', 'curly', 'coily'],
    concerns: ['dryness', 'frizz', 'breakage'],
    sizes: [{ label: '250ml', price: 30 }, { label: '500ml', price: 50 }],
    rating: 4.9, reviews: 1873,
    vessel: 'pump', tint: '#D9B9D6', badge: 'Bestseller',
    ingredients: ['Cupuaçu butter', 'Behentrimonium methosulfate', 'Squalane', 'Hydrolyzed quinoa', 'Aloe leaf juice'],
    howto: 'Rake through mid-lengths to ends after cleansing. Detangle with fingers while it sits, then leave for three minutes before rinsing.'
  },
  {
    id: 'featherlight-conditioner',
    name: 'Featherlight Conditioner',
    kind: 'Condition',
    tagline: 'Weightless volume conditioner',
    desc: 'All the softness, none of the collapse. A gel-cream that smooths the cuticle on fine and straight hair while keeping roots lifted and bouncy for days.',
    hero: 'Pea protein · hyaluronic acid',
    types: ['straight', 'wavy'],
    concerns: ['volume', 'oil'],
    sizes: [{ label: '250ml', price: 30 }, { label: '500ml', price: 50 }],
    rating: 4.7, reviews: 966,
    vessel: 'pump', tint: '#C9DCCB',
    ingredients: ['Pea protein', 'Sodium hyaluronate', 'Cetearyl alcohol', 'Panthenol', 'Green tea extract'],
    howto: 'Apply from the ears down only. Leave for one minute, rinse with cool water to seal the cuticle.'
  },
  {
    id: 'bond-mask',
    name: 'Deep Bond Mask',
    kind: 'Treat',
    tagline: 'Weekly strengthening hair mask',
    desc: 'A dense, whipped treatment that rebuilds the disulfide bonds heat, colour and bleach break apart. Hair measured 41% less breakage after four weekly uses in our lab combing tests.',
    hero: 'Maleic acid · ceramide NP · keratin amino acids',
    types: ['straight', 'wavy', 'curly', 'coily'],
    concerns: ['breakage', 'color', 'dryness'],
    sizes: [{ label: '200ml', price: 42 }],
    rating: 4.9, reviews: 3312,
    vessel: 'jar', tint: '#B98FC0', badge: 'Editor’s pick',
    ingredients: ['Maleic acid', 'Ceramide NP', 'Keratin amino acids', 'Shea butter', 'Argan oil'],
    howto: 'Once a week, after cleansing, work a generous layer through towel-dried hair. Cover with a warm towel for 10–20 minutes, then rinse thoroughly.'
  },
  {
    id: 'scalp-serum',
    name: 'Root Ritual Scalp Serum',
    kind: 'Treat',
    tagline: 'Density-supporting scalp serum',
    desc: 'A water-light dropper serum for thinning, shedding or stressed scalps. Peptides and caffeine support the growth phase while niacinamide calms redness and itch.',
    hero: 'Redensyl® · caffeine · niacinamide',
    types: ['straight', 'wavy', 'curly', 'coily'],
    concerns: ['scalp', 'volume', 'thinning'],
    sizes: [{ label: '50ml', price: 54 }],
    rating: 4.6, reviews: 1204,
    vessel: 'dropper', tint: '#E3B27F', badge: 'New',
    ingredients: ['Redensyl® peptide complex', 'Caffeine', 'Niacinamide', 'Rosemary leaf extract', 'Biotin'],
    howto: 'Part hair in sections and apply one full dropper directly to the scalp, morning or night. Massage for a minute; no need to rinse.'
  },
  {
    id: 'glass-oil',
    name: 'Glass Oil',
    kind: 'Style',
    tagline: 'Featherweight shine & seal oil',
    desc: 'A dry-touch finishing oil that coats each strand in a mirror-bright film. Seals split ends, blocks humidity for 48 hours, and never looks greasy — even on fine hair.',
    hero: 'Squalane · camellia oil · marula',
    types: ['straight', 'wavy', 'curly', 'coily'],
    concerns: ['frizz', 'shine', 'dryness'],
    sizes: [{ label: '30ml', price: 32 }, { label: '100ml', price: 68 }],
    rating: 4.8, reviews: 2687,
    vessel: 'dropper', tint: '#D7A35E', badge: 'Bestseller',
    ingredients: ['Squalane', 'Camellia seed oil', 'Marula oil', 'Vitamin E', 'Sunflower seed oil'],
    howto: 'Warm two drops between your palms and glaze over the surface of dry or damp hair. Add a third to the ends only.'
  },
  {
    id: 'curl-cream',
    name: 'Coil Cloud Curl Cream',
    kind: 'Style',
    tagline: 'Soft-hold defining cream',
    desc: 'Defines curls and coils into plump, touchable clumps with no crunch to scrunch out. Flaxseed and shea give soft, flexible hold that lasts to day three.',
    hero: 'Flaxseed · shea butter · aloe',
    types: ['curly', 'coily'],
    concerns: ['frizz', 'definition', 'dryness'],
    sizes: [{ label: '200ml', price: 34 }],
    rating: 4.8, reviews: 1590,
    vessel: 'jar', tint: '#F0C6AE',
    ingredients: ['Flaxseed extract', 'Shea butter', 'Aloe leaf juice', 'Marshmallow root', 'Glycerin'],
    howto: 'On soaking-wet hair, rake through in sections, then praying-hands the surface. Scrunch upwards and air-dry or diffuse on low.'
  },
  {
    id: 'wave-mist',
    name: 'Salt-Free Wave Mist',
    kind: 'Style',
    tagline: 'Texturizing beach-wave spray',
    desc: 'The tousled, lived-in texture of a sea spray — minus the salt that dries hair to straw. Sugar and sea-kelp give grip and piece-y movement to straight and wavy hair.',
    hero: 'Beet sugar · sea kelp',
    types: ['straight', 'wavy'],
    concerns: ['volume', 'definition'],
    sizes: [{ label: '150ml', price: 26 }],
    rating: 4.6, reviews: 811,
    vessel: 'spray', tint: '#A8C6D6',
    ingredients: ['Beet sugar', 'Sea kelp extract', 'PVP', 'Panthenol', 'Glycerin'],
    howto: 'Mist 6–8 times through damp hair, scrunch, and air-dry or rough-dry with fingers.'
  },
  {
    id: 'heat-veil',
    name: 'Heat Veil Primer',
    kind: 'Style',
    tagline: 'Thermal protectant to 230°C',
    desc: 'A weightless leave-in mist that forms a film between hair and your tools. Protects to 230°C, cuts blow-dry time by a fifth, and leaves blowouts glossy and swingy.',
    hero: 'Polyquaternium-55 · baobab protein',
    types: ['straight', 'wavy', 'curly', 'coily'],
    concerns: ['breakage', 'frizz', 'shine'],
    sizes: [{ label: '150ml', price: 29 }],
    rating: 4.7, reviews: 1422,
    vessel: 'spray', tint: '#E6D3A9',
    ingredients: ['Polyquaternium-55', 'Baobab protein', 'Hydrolyzed wheat protein', 'Glycerin', 'Amodimethicone'],
    howto: 'Mist evenly through damp or dry hair section by section before any hot tool. Comb through to distribute.'
  },
  {
    id: 'milk-leave-in',
    name: 'Milk Veil Leave-In',
    kind: 'Condition',
    tagline: 'Lightweight daily leave-in',
    desc: 'A milky lotion that detangles, softens and preps every hair type for styling. The one bottle our stylists keep in every station.',
    hero: 'Oat milk · panthenol · murumuru',
    types: ['straight', 'wavy', 'curly', 'coily'],
    concerns: ['dryness', 'frizz', 'breakage'],
    sizes: [{ label: '200ml', price: 27 }],
    rating: 4.8, reviews: 2011,
    vessel: 'tube', tint: '#EFE3D0',
    ingredients: ['Oat milk', 'Panthenol', 'Murumuru butter', 'Squalane', 'Aloe leaf juice'],
    howto: 'Smooth a walnut-sized amount through damp hair from mid-lengths down. Style as usual.'
  },
  {
    id: 'clarify-rinse',
    name: 'Reset Clarifying Rinse',
    kind: 'Cleanse',
    tagline: 'Monthly buildup-removing shampoo',
    desc: 'A once-a-month deep cleanse that dissolves hard-water minerals, silicones and product residue — so everything you use afterwards works like it did on day one.',
    hero: 'Citric acid · green clay · EDTA-free chelator',
    types: ['straight', 'wavy', 'curly', 'coily'],
    concerns: ['oil', 'scalp', 'volume'],
    sizes: [{ label: '250ml', price: 26 }],
    rating: 4.5, reviews: 604,
    vessel: 'tube', tint: '#BFD4C2',
    ingredients: ['Green clay', 'Citric acid', 'Sodium phytate', 'Decyl glucoside', 'Peppermint oil'],
    howto: 'Use in place of your regular shampoo every 2–4 weeks. Lather twice, then follow with Plush or Featherlight Conditioner.'
  },
  {
    id: 'silk-scrunchie',
    name: 'Mulberry Silk Scrunchie Trio',
    kind: 'Tools',
    tagline: '22-momme silk, no-crease hold',
    desc: 'Grade-6A mulberry silk that holds without the tug, dent or breakage of elastic bands. Three sizes, one each for buns, ponytails and sleep.',
    hero: '100% mulberry silk',
    types: ['straight', 'wavy', 'curly', 'coily'],
    concerns: ['breakage', 'frizz'],
    sizes: [{ label: 'Set of 3', price: 24 }],
    rating: 4.9, reviews: 978,
    vessel: 'scrunchie', tint: '#C7A6DE',
    ingredients: ['22-momme grade-6A mulberry silk', 'Covered elastic core'],
    howto: 'Wrap loosely; silk grips on its own. Hand-wash cool and lay flat to dry.'
  }
];

window.FOFO_BUNDLES = [
  {
    id: 'bundle-curl',
    name: 'The Curl Cloud Set',
    items: ['cloud-wash', 'plush-conditioner', 'curl-cream', 'bond-mask'],
    save: 0.2,
    note: 'Wash-day for curls & coils'
  },
  {
    id: 'bundle-volume',
    name: 'The Lift Set',
    items: ['cloud-wash', 'featherlight-conditioner', 'wave-mist', 'scalp-serum'],
    save: 0.2,
    note: 'Body for fine & straight hair'
  },
  {
    id: 'bundle-repair',
    name: 'The Rescue Set',
    items: ['bond-mask', 'heat-veil', 'glass-oil', 'silk-scrunchie'],
    save: 0.2,
    note: 'For bleached, heat-styled or breaking hair'
  }
];
